export const PRODUCT_LIST = {
    ADD: 'PRODUCT_LIST_ADD',
    DELETE: 'PRODUCT_LIST_DELETE',
    EDIT: 'PRODUCT_LIST_EDIT'
}

export const SHOPPING_CART = {
    ADD: 'SHOPPING_CART_ADD',
    DELETE: 'SHOPPING_CART_DELETE',
}


